### ISSUE TITLE
Python Repeat issue on ubuntu 22.04 with sciunit version sciunit2 0.4.post82.dev130189670

### ISSUE THREAD

**Issue by rtikmany** [depaul-dice/sciunit#14]
The python program I was auditing and re-executing is 
**Program:**
for i in range(10):
    print(i**2, end = " ")
print()

Before the exec command in /usr/lib I run
sudo find . -type d -name *pycache* -exec rm -rf {} \;

to remove all pycache folders

Then during repeat I get the error 

<img width="1504" alt="Screenshot 2023-03-10 at 11 17 35 AM" src="https://user-images.githubusercontent.com/17731125/224380759-b46183d9-b8cf-48de-ac22-87ca9792493d.png">

**Comment by sranasir** [comment]
This looks like an important issue and we should work to resolve it, especially if this behavior is going to stay as default in the future versions of Python.
There could be two potential solutions that we can investigate:
1. The ideal solution would be to make Sciunit use cached python files.
2. A temporary - and less efficient - solution would be to force all Python programs to compile from the source every time.

**Comment by moazreyad** [comment]
This issue seems to be solved with https://github.com/depaul-dice/sciunit/pull/29
