### ISSUE TITLE
sciunit repeat outputs random hex characters

### ISSUE THREAD

**Issue by kamathk98** [depaul-dice/sciunit#32]
![image](https://github.com/depaul-dice/sciunit/assets/114516826/4b7eba3d-9ab1-4e8d-82b6-af680815d8e3)

As seen in the image, repeat gives random hex digits before the desired output.

Steps to reproduce: 
1. sample.py should only contain `print("Hello from python")`
2. Run sciunit exec python3 sample.py
3. Run sciunit repeat e4

**Comment by sranasir** [comment]
Resolved by merging https://github.com/depaul-dice/provenance-to-use/pull/2

**Comment by kamathk98** [comment]
<img width="1059" alt="image" src="https://github.com/depaul-dice/sciunit/assets/114516826/1ecbd936-5bc6-4bb1-b92d-c1b1e6f34a84">
Working as expected.
