### ISSUE TITLE
Build works only once

### ISSUE THREAD

**Issue by kamathk98** [depaul-dice/sciunit#38]
When you try to build sciunit, after making a change using the instructions in build.md, it builds the first time, but gives the following error. This can lead to a lot of time wastage during development.
![image](https://github.com/depaul-dice/sciunit/assets/114516826/1e368063-4329-46ac-a055-749797c0bcf6)

A workaround for the error is to remove the line `PATCH_COMMAND ${GIT_EXECUTABLE} apply ${_FILES_DIR}/vv-report-size.patch` from CMakeLists.txt, and rebuild the code.

**Comment by sranasir** [comment]
This issue has been resolved after the commits https://github.com/depaul-dice/sciunit/commit/2990cf5adb0b0fc4420def7504a0ad5b79b97b8b and https://github.com/depaul-dice/sciunit-dedup/commit/64f496f598a4dd499c09428324110d5f4c7a1b83.
